### PR TITLE
hello rails api

### PR DESCRIPTION
**Pull request by Cluab**
### Complete Project requirements

 - Create a new Rails API app called 'hello-rails-back-end'.
 - Initialize your project with Git.
 - Make sure that your project has a Postgres database set up. 
 - Create a table for storing your messages and create 5 different greetings. 
 - Create an API endpoint that selects a random greeting from your table (you will need a controller with an action and rails route).

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @Cluab 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not follow proper Gitflow

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Cluab** [comment]
hello there @prolajumokeoni can you please explain to me how I'm not following the git-flow
because from what I understand you should create a development branch add to it all of the features and after that merge the dev branch with the main branch here's an article where you can look into it [Link](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow#:~:text=What%20is%20Gitflow%3F,lived%20branches%20and%20larger%20commits.)
and for this application, you only have one feature you can say it's like a capstone project where you only ask for one code review.
So once again can you please explain how I might not follow the git-flow

**Review by thecodechaser — APPROVED** [review]
## STATUS: APPROVED 🟢

## Hi @Cluab👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉
- Highly organized code. ✔️
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- No linter errors. :heavy_check_mark:
- PR has a good title and summary. ✔️



## Optional suggestions

- [x] The License link in the README file is broken, I would suggest fixing it to make your README file more professional.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by prolajumokeoni** [comment]
> hello there @prolajumokeoni can you please explain to me how I'm not following the git-flow because from what I understand you should create a development branch add to it all of the features and after that merge the dev branch with the main branch here's an article where you can look into it [Link](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow#:~:text=What%20is%20Gitflow%3F,lived%20branches%20and%20larger%20commits.) and for this application, you only have one feature you can say it's like a capstone project where you only ask for one code review. So once again can you please explain how I might not follow the git-flow

Hello @Cluab, from the requirements, it is clearly stated  to use Gitflow, please click on the microverse link  in your project requirements to see how to set up [Gitflow ](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md) properly

**Pull request merged**
